function getValues(){
	return {
		"rigmove_start":$val("rigmove_start"),
		"rigmove_end":$val("rigmove_end"),
		"rigmove_duration":$val("rigmove_duration"),
		"dsurface_start":$val("dsurface_start"),
		"dsurface_end":$val("dsurface_end"),
		"dsurface_duration":$val("dsurface_duration"),
		"fsurface_start":$val("fsurface_start"),
		"fsurface_end":$val("fsurface_end"),
		"fsurface_duration":$val("fsurface_duration"),
		"dintermediate_start":$val("dintermediate_start"),
		"dintermediate_end":$val("dintermediate_end"),
		"dintermediate_duration":$val("dintermediate_duration"),
		"fintermediate_start":$val("fintermediate_start"),
		"fintermediate_end":$val("fintermediate_end"),
		"fintermediate_duration":$val("fintermediate_duration"),
		"dproduction_start":$val("dproduction_start"),
		"dproduction_end":$val("dproduction_end"),
		"dproduction_duration":$val("dproduction_duration"),
		"fproduction_start":$val("fproduction_start"),
		"fproduction_end":$val("fproduction_end"),
		"fproduction_duration":$val("fproduction_duration"),
		"dliner1_start":$val("dliner1_start"),
		"dliner1_end":$val("dliner1_end"),
		"dliner1_duration":$val("dliner1_duration"),
		"fliner1_start":$val("fliner1_start"),
		"fliner1_end":$val("fliner1_end"),
		"fliner1_duration":$val("fliner1_duration"),
		"dliner2_start":$val("dliner2_start"),
		"dliner2_end":$val("dliner2_end"),
		"dliner2_duration":$val("dliner2_duration"),
		"fliner2_start":$val("fliner2_start"),
		"fliner2_	end":$val("fliner2_end"),
		"fliner2_duration":$val("fliner2_duration"),
		"dliner3_start":$val("dliner3_start"),
		"dliner3_end":$val("dliner3_end"),
		"dliner3_duration":$val("dliner3_duration"),
		"fliner3_start":$val("fliner3_start"),
		"fliner3_end":$val("fliner3_end"),
		"fliner3_duration":$val("fliner3_duration"),
		"reline_start":$val("reline_start"),
		"reline_end":$val("reline_end"),
		"reline_duration":$val("reline_duration"),
		"rigrelease_start":$val("rigrelease_start"),
		"rigrelease_end":$val("rigrelease_end"),
		"rigrelease_duration":$val("rigrelease_duration"),
		"sh-hole-size":$val("sh-hole-size"),
		"sh-case-size":$val("sh-case-size"),
		"sh-hole-depth":$val("sh-hole-depth"),
		"sh-case-depth":$val("sh-case-depth"),
		"sh-case-id":$val("sh-case-id"),
		"sh-hole-length":$val("sh-hole-length"),
		"sh-acid-section":$val("sh-acid-section"),
		"ih-hole-size":$val("ih-hole-size"),
		"ih-case-size":$val("ih-case-size"),
		"ih-hole-depth":$val("ih-hole-depth"),
		"ih-case-depth":$val("ih-case-depth"),
		"ih-case-id":$val("ih-case-id"),
		"ih-hole-length":$val("ih-hole-length"),
		"ih-acid-section":$val("ih-acid-section"),
		"dh-hole-size":$val("dh-hole-size"),
		"dh-case-size":$val("dh-case-size"),
		"dh-hole-depth":$val("dh-hole-depth"),
		"dh-case-depth":$val("dh-case-depth"),
		"dh-case-id":$val("dh-case-id"),
		"dh-hole-length":$val("dh-hole-length"),
		"dh-acid-section":$val("dh-acid-section"),
		"ph1-hole-size":$val("ph1-hole-size"),
		"ph1-case-size":$val("ph1-case-size"),
		"ph1-hole-depth":$val("ph1-hole-depth"),
		"ph1-case-depth":$val("ph1-case-depth"),
		"ph1-case-id":$val("ph1-case-id"),
		"ph1-hole-length":$val("ph1-hole-length"),
		"ph1-acid-section":$val("ph1-acid-section"),
		"ph2-hole-size":$val("ph2-hole-size"),
		"ph2-case-size":$val("ph2-case-size"),
		"ph2-hole-depth":$val("ph2-hole-depth"),
		"ph2-case-depth":$val("ph2-case-depth"),
		"ph2-case-id":$val("ph2-case-id"),
		"ph2-hole-length":$val("ph2-hole-length"),
		"ph2-acid-section":$val("ph2-acid-section"),
		"ph3-hole-size":$val("ph3-hole-size"),
		"ph3-case-size":$val("ph3-case-size"),
		"ph3-hole-depth":$val("ph3-hole-depth"),
		"ph3-case-depth":$val("ph3-case-depth"),
		"ph3-case-id":$val("ph3-case-id"),
		"ph3-hole-length":$val("ph3-hole-length"),
		"ph3-acid-section":$val("ph3-acid-section"),
		"reline-hole-size":$val("reline-hole-size"),
		"reline-case-size":$val("reline-case-size"),
		"reline-hole-depth":$val("reline-hole-depth"),
		"reline-case-depth":$val("reline-case-depth"),
		"reline-case-id":$val("reline-case-id"),
		"reline-hole-length":$val("reline-hole-length"),
		"reline-acid-section":$val("reline-acid-section"),
		"reline_DRLG":$val("reline_DRLG"),
		"reline_FLAT":$val("reline_FLAT"),
		"reline_cement_plug":$val("reline_cement_plug"),
		"reline_top_job":$val("reline_top_job"),
		"casing_surface":$val("casing_surface"),
		"casing_intermediate":$val("casing_intermediate"),
		"casing_production":$val("casing_production"),
		"casing_production_liner_1":$val("casing_production_liner_1"),
		"casing_production_liner_2":$val("casing_production_liner_2"),
		"casing_production_liner_3":$val("casing_production_liner_3"),
		"casing_reline":$val("casing_reline"),
		"surface_DRLG":$val("surface_DRLG"),
		"surface_FLAT":$val("surface_FLAT"),
		"intermediate_DRLG":$val("intermediate_DRLG"),
		"intermediate_FLAT":$val("intermediate_FLAT"),
		"production_casing_DRLG":$val("production_casing_DRLG"),
		"production_casing_FLAT":$val("production_casing_FLAT"),
		"production_liner_1_DRLG":$val("production_liner_1_DRLG"),
		"production_liner_1_FLAT":$val("production_liner_1_FLAT"),
		"production_liner_2_DRLG":$val("production_liner_2_DRLG"),
		"production_liner_2_FLAT":$val("production_liner_2_FLAT"),
		"production_liner_3_DRLG":$val("production_liner_3_DRLG"),
		"production_liner_3_FLAT":$val("production_liner_3_FLAT"),
		"well_name":$val("well_name"),
		"target_depth":$val("target_depth"),
		"no_of_joints":$val("no_of_joints"),
		"target_rop":$val("target_rop"),
		"forex_php_us":$val("forex_php_us"),
		"diesel_php_us":$val("diesel_php_us"),
		"surface_cement_plug":$val("surface_cement_plug"),
		"surface_top_job":$val("surface_top_job"),
		"intermediate_cement_plug":$val("intermediate_cement_plug"),
		"intermediate_top_job":$val("intermediate_top_job"),
		"production_casing_cement_plug":$val("production_casing_cement_plug"),
		"production_casing_top_job":$val("production_casing_top_job"),
		"production_liner_1_cement_plug":$val("production_liner_1_cement_plug"),
		"production_liner_1_top_job":$val("production_liner_1_top_job"),
		"production_liner_2_cement_plug":$val("production_liner_2_cement_plug"),
		"production_liner_2_top_job":$val("production_liner_2_top_job"),
		"production_liner_3_cement_plug":$val("production_liner_3_cement_plug"),
		"production_liner_3_top_job":$val("production_liner_3_top_job"),
		"rig":$val("rig"),
		"rh_bh":$val("rh_bh"),
		"double_liner":$val("double_liner"),
		"aerated_surface":$val("aerated_surface"),
		"aerated_production_intermediate":$val("aerated_production_intermediate"),
		"aerated_production_casing":$val("aerated_production_casing"),
		"aerated_production_liner_1":$val("aerated_production_liner_1"),
		"aerated_production_liner_2":$val("aerated_production_liner_2"),
		"reg_bottom_bh":$val("reg_bottom_bh"),
		"rent_drill_pipes":$val("rent_drill_pipes"),
		"mob_demob_drillpipes":$val("mob_demob_drillpipes"),
		"yes_wo_preinstalled_casing":$val("yes_wo_preinstalled_casing"),
		"prod_liner_3":$val("prod_liner_3"),
		"interisland_rigmove":$val("interisland_rigmove"),
		"total_days":$val("total_days"),
		"drilling_days":$val("drilling_days"),
		"project_location":$val("project_location"),
		"rig_move_from":$val("rig_move_from"),
		"rig_move_days":$val("rig_move_days"),
		"dhv_1":$val("dhv_1"),
		"dhv_2":$val("dhv_2"),
		"pwd_fliner_1":$val("pwd_fliner_1"),
		"pwd_fliner_2":$val("pwd_fliner_2"),
		"chf":$val("chf"),
		"mud_logging":$val("mud_logging"),
		"formation_eval_fliner_1":$val("formation_eval_fliner_1"),
		"formation_eval_fliner_2":$val("formation_eval_fliner_2"),
		"reline":$val("reline"),
		// Hole Case Assumptions
		"hole_bh_surface":$val("hole_bh_surface"),
		"hole_rh_surface":$val("hole_rh_surface"),
		"case_bh_surface":$val("case_bh_surface"),
		"case_rh_surface":$val("case_rh_surface"),
		//
		"hole_bh_intermediate":$val("hole_bh_intermediate"),
		"hole_rh_intermediate":$val("hole_rh_intermediate"),
		"case_bh_intermediate":$val("case_bh_intermediate"),
		"case_rh_intermediate":$val("case_rh_intermediate"),
		//
		"hole_bh_prodn_casing":$val("hole_bh_prodn_casing"),
		"hole_rh_prodn_casing":$val("hole_rh_prodn_casing"),
		"case_bh_prodn_casing":$val("case_bh_prodn_casing"),
		"case_rh_prodn_casing":$val("case_rh_prodn_casing"),
		//
		"hole_bh_prodn_liner_1":$val("hole_bh_prodn_liner_1"),
		"hole_rh_prodn_liner_1":$val("hole_rh_prodn_liner_1"),
		"case_bh_prodn_liner_1":$val("case_bh_prodn_liner_1"),
		"case_rh_prodn_liner_1":$val("case_rh_prodn_liner_1"),
		//
		"hole_bh_prodn_liner_2":$val("hole_bh_prodn_liner_2"),
		"hole_rh_prodn_liner_2":$val("hole_rh_prodn_liner_2"),
		"case_bh_prodn_liner_2":$val("case_bh_prodn_liner_2"),
		"case_rh_prodn_liner_2":$val("case_rh_prodn_liner_2"),
		//
		"hole_bh_prodn_liner_3":$val("hole_bh_prodn_liner_3"),
		"hole_rh_prodn_liner_3":$val("hole_rh_prodn_liner_3"),
		"case_bh_prodn_liner_3":$val("case_bh_prodn_liner_3"),
		"case_rh_prodn_liner_3":$val("case_rh_prodn_liner_3"),
		// Other Hole Case Assumptions
		"other_hole_asmpt_surface":$val("other_hole_asmpt_surface"),
		"other_case_asmpt_surface":$val("other_case_asmpt_surface"),
		"other_id_asmpt_surface":$val("other_id_asmpt_surface"),
		//
		"other_hole_asmpt_intermediate":$val("other_hole_asmpt_intermediate"),
		"other_case_asmpt_intermediate":$val("other_case_asmpt_intermediate"),
		"other_id_asmpt_intermediate":$val("other_id_asmpt_intermediate"),
		//
		"other_hole_asmpt_prodn_casing":$val("other_hole_asmpt_prodn_casing"),
		"other_case_asmpt_prodn_casing":$val("other_case_asmpt_prodn_casing"),
		"other_id_asmpt_prodn_casing":$val("other_id_asmpt_prodn_casing"),
		//
		"other_hole_asmpt_prodn_liner_1":$val("other_hole_asmpt_prodn_liner_1"),
		"other_case_asmpt_prodn_liner_1":$val("other_case_asmpt_prodn_liner_1"),
		"other_id_asmpt_prodn_liner_1":$val("other_id_asmpt_prodn_liner_1"),
		//
		"other_hole_asmpt_prodn_liner_2":$val("other_hole_asmpt_prodn_liner_2"),
		"other_case_asmpt_prodn_liner_2":$val("other_case_asmpt_prodn_liner_2"),
		"other_id_asmpt_prodn_liner_2":$val("other_id_asmpt_prodn_liner_2"),
		//
		"other_hole_asmpt_prodn_liner_3":$val("other_hole_asmpt_prodn_liner_3"),
		"other_case_asmpt_prodn_liner_3":$val("other_case_asmpt_prodn_liner_3"),
		"other_id_asmpt_prodn_liner_3":$val("other_id_asmpt_prodn_liner_3"),
		//
		"other_hole_asmpt_no_label_1":$val("other_hole_asmpt_no_label_1"),
		"other_case_asmpt_no_label_1":$val("other_case_asmpt_no_label_1"),
		"other_id_asmpt_no_label_1":$val("other_id_asmpt_no_label_1"),
		//
		"other_hole_asmpt_no_label_2":$val("other_hole_asmpt_no_label_2"),
		"other_case_asmpt_no_label_2":$val("other_case_asmpt_no_label_2"),
		"other_id_asmpt_no_label_2":$val("other_id_asmpt_no_label_2"),
		//
		"other_hole_asmpt_no_label_3":$val("other_hole_asmpt_no_label_3"),
		"other_case_asmpt_no_label_3":$val("other_case_asmpt_no_label_3"),
		"other_id_asmpt_no_label_3":$val("other_id_asmpt_no_label_3"),
		// casing id
		"casing_id_bh_surface":$val("casing_id_bh_surface"),
		"casing_id_rh_surface":$val("casing_id_rh_surface"),
		//
		"casing_id_bh_intermediate":$val("casing_id_bh_intermediate"),
		"casing_id_rh_intermediate":$val("casing_id_rh_intermediate"),
		//
		"casing_id_bh_prodn_casing":$val("casing_id_bh_prodn_casing"),
		"casing_id_rh_prodn_casing":$val("casing_id_rh_prodn_casing"),
		//
		"casing_id_bh_prodn_liner_1":$val("casing_id_bh_prodn_liner_1"),
		"casing_id_rh_prodn_liner_1":$val("casing_id_rh_prodn_liner_1"),
		//
		"casing_id_bh_prodn_liner_2":$val("casing_id_bh_prodn_liner_2"),
		"casing_id_rh_prodn_liner_2":$val("casing_id_rh_prodn_liner_2"),
		//
		"casing_id_bh_prodn_liner_3":$val("casing_id_bh_prodn_liner_3"),
		"casing_id_rh_prodn_liner_3":$val("casing_id_rh_prodn_liner_3"),
		//
		"casing_id_bh_reline":$val("casing_id_bh_reline"),
		"casing_id_rh_reline":$val("casing_id_rh_reline"),
		//cement acid
		"cement_surface":$val("cement_surface"),
		"acid_surface":$val("acid_surface"),
		"top_job_surface":$val("top_job_surface"),
		//
		"cement_intermediate":$val("cement_intermediate"),
		"acid_intermediate":$val("acid_intermediate"),
		"top_job_intermediate":$val("top_job_intermediate"),
		//
		"cement_prodn_casing":$val("cement_prodn_casing"),
		"acid_prodn_casing":$val("acid_prodn_casing"),
		"top_job_prodn_casing":$val("top_job_prodn_casing"),
		//
		"cement_prodn_liner_1":$val("cement_prodn_liner_1"),
		"acid_prodn_liner_1":$val("acid_prodn_liner_1"),
		"top_job_prodn_liner_1":$val("top_job_prodn_liner_1"),
		//
		"cement_prodn_liner_2":$val("cement_prodn_liner_2"),
		"acid_prodn_liner_2":$val("acid_prodn_liner_2"),
		"top_job_prodn_liner_2":$val("top_job_prodn_liner_2"),
		//
		"cement_prodn_liner_3":$val("cement_prodn_liner_3"),
		"acid_prodn_liner_3":$val("acid_prodn_liner_3"),
		"top_job_prodn_liner_3":$val("top_job_prodn_liner_3"),
		// tpwsri
		"tpwsri_ave_rop_rate":$val("tpwsri_ave_rop_rate"),
		"tpwsri_base_day_rate":$val("tpwsri_base_day_rate"),
		"tpwsri_standby_rate":$val("tpwsri_standby_rate"),
		"tpwsri_movefee":$val("tpwsri_movefee"),
		"tpwsri_rigmove_rate":$val("tpwsri_rigmove_rate"),
		"tpwsri_additional_payment":$val("tpwsri_additional_payment"),
		"tpwsri_penalty_payment":$val("tpwsri_penalty_payment"),
		"tpwsri_well_bonus":$val("tpwsri_well_bonus"),
		"tpwsri_well_rop_bonus":$val("tpwsri_well_rop_bonus"),
		// export cover sheet and cost details
		"export_cover_cost_tables":$val("export-table-cover-sheets-cost-details"),
		
		
		// analysis casing depth
		"analysis_rop_sh_cd"  : $val("analysis-rop-sh-cd"),
		"analysis_rop_ih_cd"  : $val("analysis-rop-ih-cd"),
		"analysis_rop_dh_cd"  : $val("analysis-rop-dh-cd"),
		"analysis_rop_ph1_cd" : $val("analysis-rop-ph1-cd"),
		"analysis_rop_ph2_cd" : $val("analysis-rop-ph2-cd"),


		// analysis target rop baseline increment
		"analysis_rop_sh_inc_b"  : $val("analysis-rop-sh-inc-b"),
		"analysis_rop_ih_inc_b"  : $val("analysis-rop-ih-inc-b"),
		"analysis_rop_dh_inc_b"  : $val("analysis-rop-dh-inc-b"),
		"analysis_rop_ph1_inc_b" : $val("analysis-rop-ph1-inc-b"),
		"analysis_rop_ph2_inc_b" : $val("analysis-rop-ph2-inc-b"),


		// analysis target rop first increment
		"analysis_rop_sh_inc_1"  : $val("analysis-rop-sh-inc-1"),
		"analysis_rop_ih_inc_1"  : $val("analysis-rop-ih-inc-1"),
		"analysis_rop_dh_inc_1"  : $val("analysis-rop-dh-inc-1"),
		"analysis_rop_ph1_inc_1" : $val("analysis-rop-ph1-inc-1"),
		"analysis_rop_ph2_inc_1" : $val("analysis-rop-ph2-inc-1"),


		// analysis target rop second increment
		"analysis_rop_sh_inc_2"  : $val("analysis-rop-sh-inc-2"),
		"analysis_rop_ih_inc_2"  : $val("analysis-rop-ih-inc-2"),
		"analysis_rop_dh_inc_2"  : $val("analysis-rop-dh-inc-2"),
		"analysis_rop_ph1_inc_2" : $val("analysis-rop-ph1-inc-2"),
		"analysis_rop_ph2_inc_2" : $val("analysis-rop-ph2-inc-2"),


		// analysis target rop three increment
		"analysis_rop_sh_inc_3"  : $val("analysis-rop-sh-inc-3"),
		"analysis_rop_ih_inc_3"  : $val("analysis-rop-ih-inc-3"),
		"analysis_rop_dh_inc_3"  : $val("analysis-rop-dh-inc-3"),
		"analysis_rop_ph1_inc_3" : $val("analysis-rop-ph1-inc-3"),
		"analysis_rop_ph2_inc_3" : $val("analysis-rop-ph2-inc-3"),
		

		// analysis day b
		"analysis_rop_sh_day_b"  : $val("analysis-rop-sh-day-b"),
		"analysis_rop_ih_day_b"  : $val("analysis-rop-ih-day-b"),
		"analysis_rop_dh_day_b"  : $val("analysis-rop-dh-day-b"),
		"analysis_rop_ph1_day_b" : $val("analysis-rop-ph1-day-b"),
		"analysis_rop_ph2_day_b" : $val("analysis-rop-ph2-day-b"),

		// analysis day 1
		"analysis_rop_sh_day_1"  : $val("analysis-rop-sh-day-1"),
		"analysis_rop_ih_day_1"  : $val("analysis-rop-ih-day-1"),
		"analysis_rop_dh_day_1"  : $val("analysis-rop-dh-day-1"),
		"analysis_rop_ph1_day_1" : $val("analysis-rop-ph1-day-1"),
		"analysis_rop_ph2_day_1" : $val("analysis-rop-ph2-day-1"),

		// analysis day 2
		"analysis_rop_sh_day_2"  : $val("analysis-rop-sh-day-2"),
		"analysis_rop_ih_day_2"  : $val("analysis-rop-ih-day-2"),
		"analysis_rop_dh_day_2"  : $val("analysis-rop-dh-day-2"),
		"analysis_rop_ph1_day_2" : $val("analysis-rop-ph1-day-2"),
		"analysis_rop_ph2_day_2" : $val("analysis-rop-ph2-day-2"),

		// analysis day 3
		"analysis_rop_sh_day_3"  : $val("analysis-rop-sh-day-3"),
		"analysis_rop_ih_day_3"  : $val("analysis-rop-ih-day-3"),
		"analysis_rop_dh_day_3"  : $val("analysis-rop-dh-day-3"),
		"analysis_rop_ph1_day_3" : $val("analysis-rop-ph1-day-3"),
		"analysis_rop_ph2_day_3" : $val("analysis-rop-ph2-day-3"),
		//
		// Analysis Changing Casing Depth
		//
		// analysis day b
		"analysis_cd_sh_day_b"  : $val("analysis-cd-sh-day-b"),
		"analysis_cd_ih_day_b"  : $val("analysis-cd-ih-day-b"),
		"analysis_cd_dh_day_b"  : $val("analysis-cd-dh-day-b"),
		"analysis_cd_ph1_day_b" : $val("analysis-cd-ph1-day-b"),
		"analysis_cd_ph2_day_b" : $val("analysis-cd-ph2-day-b"),

		// analysis day 1
		"analysis_cd_sh_day_1"  : $val("analysis-cd-sh-day-1"),
		"analysis_cd_ih_day_1"  : $val("analysis-cd-ih-day-1"),
		"analysis_cd_dh_day_1"  : $val("analysis-cd-dh-day-1"),
		"analysis_cd_ph1_day_1" : $val("analysis-cd-ph1-day-1"),
		"analysis_cd_ph2_day_1" : $val("analysis-cd-ph2-day-1"),

		// analysis day 2
		"analysis_cd_sh_day_2"  : $val("analysis-cd-sh-day-2"),
		"analysis_cd_ih_day_2"  : $val("analysis-cd-ih-day-2"),
		"analysis_cd_dh_day_2"  : $val("analysis-cd-dh-day-2"),
		"analysis_cd_ph1_day_2" : $val("analysis-cd-ph1-day-2"),
		"analysis_cd_ph2_day_2" : $val("analysis-cd-ph2-day-2"),

		// analysis day 3
		"analysis_cd_sh_day_3"  : $val("analysis-cd-sh-day-3"),
		"analysis_cd_ih_day_3"  : $val("analysis-cd-ih-day-3"),
		"analysis_cd_dh_day_3"  : $val("analysis-cd-dh-day-3"),
		"analysis_cd_ph1_day_3" : $val("analysis-cd-ph1-day-3"),
		"analysis_cd_ph2_day_3" : $val("analysis-cd-ph2-day-3"),

		// Casing Depth
		"analysis_sh_cd"  : $val("analysis-sh-cd-b"),
		"analysis_ih_cd"  : $val("analysis-ih-cd-b"),
		"analysis_dh_cd"  : $val("analysis-dh-cd-b"),
		"analysis_ph1_cd" : $val("analysis-ph1-cd-b"),
		"analysis_ph2_cd" : $val("analysis-ph2-cd-b"),
		// Casing Depth Increment
		// - surface
		"analysis_sh_cd_1"  : $val("analysis-sh-cd-1"),
		"analysis_sh_cd_2"  : $val("analysis-sh-cd-2"),
		"analysis_sh_cd_3"  : $val("analysis-sh-cd-3"),
		// - intermediate
		"analysis_ih_cd_1"  : $val("analysis-ih-cd-1"),
		"analysis_ih_cd_2"  : $val("analysis-ih-cd-2"),
		"analysis_ih_cd_3"  : $val("analysis-ih-cd-3"),
		// - production casing
		"analysis_dh_cd_1"  : $val("analysis-dh-cd-1"),
		"analysis_dh_cd_2"  : $val("analysis-dh-cd-2"),
		"analysis_dh_cd_3"  : $val("analysis-dh-cd-3"),
		// - production liner 1
		"analysis_ph1_cd_1"  : $val("analysis-ph1-cd-1"),
		"analysis_ph1_cd_2"  : $val("analysis-ph1-cd-2"),
		"analysis_ph1_cd_3"  : $val("analysis-ph1-cd-3"),
		// - production liner 2
		"analysis_ph2_cd_1"  : $val("analysis-ph2-cd-1"),
		"analysis_ph2_cd_2"  : $val("analysis-ph2-cd-2"),
		"analysis_ph2_cd_3"  : $val("analysis-ph2-cd-3"),

		// Cost Details Item Costs
		// Fuel Quantity
		"fuel_qty_item0" : $val("fuel-qty-item0"),
		"fuel_qty_item1" : $val("fuel-qty-item1"),
		"fuel_qty_item2" : $val("fuel-qty-item2"),
		"fuel_qty_item3" : $val("fuel-qty-item3"),
		"fuel_qty_item4" : $val("fuel-qty-item4"),
		"fuel_qty_item5" : $val("fuel-qty-item5"),
		
		// Fuel Costs
		"fuel_cost_item0" : $val("fuel-cost-item0"),
		"fuel_cost_item1" : $val("fuel-cost-item1"),
		"fuel_cost_item2" : $val("fuel-cost-item2"),
		"fuel_cost_item3" : $val("fuel-cost-item3"),
		"fuel_cost_item4" : $val("fuel-cost-item4"),
		"fuel_cost_item5" : $val("fuel-cost-item5"),

		// Mud Chemicals Costs
		"mudchemicals_cost_item0" : $val("mudchemicals-cost-item0"),
		"mudchemicals_cost_item1" : $val("mudchemicals-cost-item1"),
		"mudchemicals_cost_item2" : $val("mudchemicals-cost-item2"),
		"mudchemicals_cost_item3" : $val("mudchemicals-cost-item3"),
		"mudchemicals_cost_item4" : $val("mudchemicals-cost-item4"),
		"mudchemicals_cost_item5" : $val("mudchemicals-cost-item5"),
		"mudchemicals_cost_item6" : $val("mudchemicals-cost-item6"),
		"mudchemicals_cost_item7" : $val("mudchemicals-cost-item7"),
		"mudchemicals_cost_item8" : $val("mudchemicals-cost-item8"),
		"mudchemicals_cost_item9" : $val("mudchemicals-cost-item9"),
		"mudchemicals_cost_item10" : $val("mudchemicals-cost-item10"),
		"mudchemicals_cost_item11" : $val("mudchemicals-cost-item11"),
		"mudchemicals_cost_item12" : $val("mudchemicals-cost-item12"),
		"mudchemicals_cost_item13" : $val("mudchemicals-cost-item13"),
		"mudchemicals_cost_item14" : $val("mudchemicals-cost-item14"),
		"mudchemicals_cost_item15" : $val("mudchemicals-cost-item15"),
		"mudchemicals_cost_item16" : $val("mudchemicals-cost-item16"),
		"mudchemicals_cost_item17" : $val("mudchemicals-cost-item17"),
		"mudchemicals_cost_item18" : $val("mudchemicals-cost-item18"),
		"mudchemicals_cost_item19" : $val("mudchemicals-cost-item19"),
		"mudchemicals_cost_item20" : $val("mudchemicals-cost-item20"),
		"mudchemicals_cost_item21" : $val("mudchemicals-cost-item21"),
		"mudchemicals_cost_item22" : $val("mudchemicals-cost-item22"),
		"mudchemicals_cost_item23" : $val("mudchemicals-cost-item23"),
		"mudchemicals_cost_item24" : $val("mudchemicals-cost-item24"),
		"mudchemicals_cost_item25" : $val("mudchemicals-cost-item25"),
		"mudchemicals_cost_item26" : $val("mudchemicals-cost-item26"),
		"mudchemicals_cost_item27" : $val("mudchemicals-cost-item27"),
		"mudchemicals_cost_item28" : $val("mudchemicals-cost-item28"),

		// Cement Additives Costs
		"cement_additives_cost_item0" : $val("cement-additives-cost-item0"),
		"cement_additives_cost_item1" : $val("cement-additives-cost-item1"),
		"cement_additives_cost_item2" : $val("cement-additives-cost-item2"),
		"cement_additives_cost_item3" : $val("cement-additives-cost-item3"),
		"cement_additives_cost_item4" : $val("cement-additives-cost-item4"),
		"cement_additives_cost_item5" : $val("cement-additives-cost-item5"),
		"cement_additives_cost_item6" : $val("cement-additives-cost-item6"),
		"cement_additives_cost_item7" : $val("cement-additives-cost-item7"),
		"cement_additives_cost_item8" : $val("cement-additives-cost-item8"),
		"cement_additives_cost_item9" : $val("cement-additives-cost-item9"),
		"cement_additives_cost_item10" : $val("cement-additives-cost-item10"),
		
		// Rockbits Smith
		"rockbits_smith_cost_item0" : $val("rockbits-smith-cost-item0"),
		"rockbits_smith_cost_item1" : $val("rockbits-smith-cost-item1"),
		"rockbits_smith_cost_item2" : $val("rockbits-smith-cost-item2"),
		"rockbits_smith_cost_item3" : $val("rockbits-smith-cost-item3"),
		"rockbits_smith_cost_item4" : $val("rockbits-smith-cost-item4"),
		"rockbits_smith_cost_item5" : $val("rockbits-smith-cost-item5"),
		"rockbits_smith_cost_item6" : $val("rockbits-smith-cost-item6"),
		"rockbits_smith_cost_item7" : $val("rockbits-smith-cost-item7"),
		"rockbits_smith_cost_item8" : $val("rockbits-smith-cost-item8"),
		"rockbits_smith_cost_item9" : $val("rockbits-smith-cost-item9"),
		"rockbits_smith_cost_item10" : $val("rockbits-smith-cost-item10"),
		"rockbits_smith_cost_item11" : $val("rockbits-smith-cost-item11"),
		"rockbits_smith_cost_item12" : $val("rockbits-smith-cost-item12"),
		"rockbits_smith_cost_item13" : $val("rockbits-smith-cost-item13"),
		"rockbits_smith_cost_item14" : $val("rockbits-smith-cost-item14"),
		"rockbits_smith_cost_item15" : $val("rockbits-smith-cost-item15"),
		"rockbits_smith_cost_item16" : $val("rockbits-smith-cost-item16"),
		"rockbits_smith_cost_item17" : $val("rockbits-smith-cost-item17"),
		"rockbits_smith_cost_item18" : $val("rockbits-smith-cost-item18"),
		"rockbits_smith_cost_item19" : $val("rockbits-smith-cost-item19"),
		"rockbits_smith_cost_item20" : $val("rockbits-smith-cost-item20"),
		"rockbits_smith_cost_item21" : $val("rockbits-smith-cost-item21"),
		"rockbits_smith_cost_item22" : $val("rockbits-smith-cost-item22"),
		"rockbits_smith_cost_item23" : $val("rockbits-smith-cost-item23"),
		"rockbits_smith_cost_item24" : $val("rockbits-smith-cost-item24"),
		"rockbits_smith_cost_item25" : $val("rockbits-smith-cost-item25"),
		"rockbits_smith_cost_item26" : $val("rockbits-smith-cost-item26"),
		"rockbits_smith_cost_item27" : $val("rockbits-smith-cost-item27"),

		// Rockbits Hughes
		"rockbits_hughes_cost_item0" : $val("rockbits-hughes-cost-item0"),
		"rockbits_hughes_cost_item1" : $val("rockbits-hughes-cost-item1"),
		"rockbits_hughes_cost_item2" : $val("rockbits-hughes-cost-item2"),
		"rockbits_hughes_cost_item3" : $val("rockbits-hughes-cost-item3"),
		"rockbits_hughes_cost_item4" : $val("rockbits-hughes-cost-item4"),
		"rockbits_hughes_cost_item5" : $val("rockbits-hughes-cost-item5"),
		"rockbits_hughes_cost_item6" : $val("rockbits-hughes-cost-item6"),
		"rockbits_hughes_cost_item7" : $val("rockbits-hughes-cost-item7"),
		"rockbits_hughes_cost_item8" : $val("rockbits-hughes-cost-item8"),
		"rockbits_hughes_cost_item9" : $val("rockbits-hughes-cost-item9"),
		"rockbits_hughes_cost_item10" : $val("rockbits-hughes-cost-item10"),
		"rockbits_hughes_cost_item11" : $val("rockbits-hughes-cost-item11"),
		"rockbits_hughes_cost_item12" : $val("rockbits-hughes-cost-item12"),
		"rockbits_hughes_cost_item13" : $val("rockbits-hughes-cost-item13"),
		"rockbits_hughes_cost_item14" : $val("rockbits-hughes-cost-item14"),
		"rockbits_hughes_cost_item15" : $val("rockbits-hughes-cost-item15"),
		"rockbits_hughes_cost_item16" : $val("rockbits-hughes-cost-item16"),
		"rockbits_hughes_cost_item17" : $val("rockbits-hughes-cost-item17"),
		"rockbits_hughes_cost_item18" : $val("rockbits-hughes-cost-item18"),
		"rockbits_hughes_cost_item19" : $val("rockbits-hughes-cost-item19"),
		"rockbits_hughes_cost_item20" : $val("rockbits-hughes-cost-item20"),
		"rockbits_hughes_cost_item21" : $val("rockbits-hughes-cost-item21"),
		"rockbits_hughes_cost_item22" : $val("rockbits-hughes-cost-item22"),
		"rockbits_hughes_cost_item23" : $val("rockbits-hughes-cost-item23"),
		"rockbits_hughes_cost_item24" : $val("rockbits-hughes-cost-item24"),
		"rockbits_hughes_cost_item25" : $val("rockbits-hughes-cost-item25"),
		"rockbits_hughes_cost_item26" : $val("rockbits-hughes-cost-item26"),
		"rockbits_hughes_cost_item27" : $val("rockbits-hughes-cost-item27"),

		// Drilling Supplies
		"drilling_supplies_cost_item0" : $val("drilling-supplies-cost-item0"),
		"drilling_supplies_cost_item1" : $val("drilling-supplies-cost-item1"),

		// Wellhead
		"wellhead_cost_item0" : $val("wellhead-cost-item0"),
		"wellhead_cost_item1" : $val("wellhead-cost-item1"),
		"wellhead_cost_item2" : $val("wellhead-cost-item2"),
		"wellhead_cost_item3" : $val("wellhead-cost-item3"),
		"wellhead_cost_item4" : $val("wellhead-cost-item4"),

		// Cementing Services
		"cementing_services_cost_item0" : $val("cementing-services-cost-item0"),
		"cementing_services_cost_item1" : $val("cementing-services-cost-item1"),
		"cementing_services_cost_item2" : $val("cementing-services-cost-item2"),
		"cementing_services_cost_item3" : $val("cementing-services-cost-item3"),
		"cementing_services_cost_item4" : $val("cementing-services-cost-item4"),
		"cementing_services_cost_item5" : $val("cementing-services-cost-item5"),
		"cementing_services_cost_item6" : $val("cementing-services-cost-item6"),
		"cementing_services_cost_item7" : $val("cementing-services-cost-item7"),
		"cementing_services_cost_item8" : $val("cementing-services-cost-item8"),
		"cementing_services_cost_item9" : $val("cementing-services-cost-item9"),
		"cementing_services_cost_item10" : $val("cementing-services-cost-item10"),
		"cementing_services_cost_item11" : $val("cementing-services-cost-item11"),
		"cementing_services_cost_item12" : $val("cementing-services-cost-item12"),

		// Directional Drilling Qty
		"directional_drilling_qty_item0" : $val("directional-drilling-qty-item0"),
		"directional_drilling_qty_item1" : $val("directional-drilling-qty-item1"),
		"directional_drilling_qty_item2" : $val("directional-drilling-qty-item2"),
		"directional_drilling_qty_item3" : $val("directional-drilling-qty-item3"),
		"directional_drilling_qty_item4" : $val("directional-drilling-qty-item4"),
		"directional_drilling_qty_item5" : $val("directional-drilling-qty-item5"),
		"directional_drilling_qty_item6" : $val("directional-drilling-qty-item6"),
		"directional_drilling_qty_item7" : $val("directional-drilling-qty-item7"),
		"directional_drilling_qty_item8" : $val("directional-drilling-qty-item8"),
		"directional_drilling_qty_item9" : $val("directional-drilling-qty-item9"),
		"directional_drilling_qty_item10" : $val("directional-drilling-qty-item10"),
		"directional_drilling_qty_item11" : $val("directional-drilling-qty-item11"),
		"directional_drilling_qty_item12" : $val("directional-drilling-qty-item12"),
		"directional_drilling_qty_item13" : $val("directional-drilling-qty-item13"),
		"directional_drilling_qty_item14" : $val("directional-drilling-qty-item14"),
		"directional_drilling_qty_item15" : $val("directional-drilling-qty-item15"),
		"directional_drilling_qty_item16" : $val("directional-drilling-qty-item16"),
		"directional_drilling_qty_item17" : $val("directional-drilling-qty-item17"),
		"directional_drilling_qty_item18" : $val("directional-drilling-qty-item18"),
		"directional_drilling_qty_item19" : $val("directional-drilling-qty-item19"),
		"directional_drilling_qty_item20" : $val("directional-drilling-qty-item20"),
		"directional_drilling_qty_item21" : $val("directional-drilling-qty-item21"),
		"directional_drilling_qty_item22" : $val("directional-drilling-qty-item22"),
		"directional_drilling_qty_item23" : $val("directional-drilling-qty-item23"),
		"directional_drilling_qty_item24" : $val("directional-drilling-qty-item24"),
		"directional_drilling_qty_item25" : $val("directional-drilling-qty-item25"),
		"directional_drilling_qty_item26" : $val("directional-drilling-qty-item26"),
		"directional_drilling_qty_item27" : $val("directional-drilling-qty-item27"),
		"directional_drilling_qty_item28" : $val("directional-drilling-qty-item28"),
		"directional_drilling_qty_item29" : $val("directional-drilling-qty-item29"),
		"directional_drilling_qty_item30" : $val("directional-drilling-qty-item30"),
		"directional_drilling_qty_item31" : $val("directional-drilling-qty-item31"),

		// Directional Drilling Cost
		"directional_drilling_cost_item0" : $val("directional-drilling-cost-item0"),
		"directional_drilling_cost_item1" : $val("directional-drilling-cost-item1"),
		"directional_drilling_cost_item2" : $val("directional-drilling-cost-item2"),
		"directional_drilling_cost_item3" : $val("directional-drilling-cost-item3"),
		"directional_drilling_cost_item4" : $val("directional-drilling-cost-item4"),
		"directional_drilling_cost_item5" : $val("directional-drilling-cost-item5"),
		"directional_drilling_cost_item6" : $val("directional-drilling-cost-item6"),
		"directional_drilling_cost_item7" : $val("directional-drilling-cost-item7"),
		"directional_drilling_cost_item8" : $val("directional-drilling-cost-item8"),
		"directional_drilling_cost_item9" : $val("directional-drilling-cost-item9"),
		"directional_drilling_cost_item10" : $val("directional-drilling-cost-item10"),
		"directional_drilling_cost_item11" : $val("directional-drilling-cost-item11"),
		"directional_drilling_cost_item12" : $val("directional-drilling-cost-item12"),
		"directional_drilling_cost_item13" : $val("directional-drilling-cost-item13"),
		"directional_drilling_cost_item14" : $val("directional-drilling-cost-item14"),
		"directional_drilling_cost_item15" : $val("directional-drilling-cost-item15"),
		"directional_drilling_cost_item16" : $val("directional-drilling-cost-item16"),
		"directional_drilling_cost_item17" : $val("directional-drilling-cost-item17"),
		"directional_drilling_cost_item18" : $val("directional-drilling-cost-item18"),
		"directional_drilling_cost_item19" : $val("directional-drilling-cost-item19"),
		"directional_drilling_cost_item20" : $val("directional-drilling-cost-item20"),
		"directional_drilling_cost_item21" : $val("directional-drilling-cost-item21"),
		"directional_drilling_cost_item22" : $val("directional-drilling-cost-item22"),
		"directional_drilling_cost_item23" : $val("directional-drilling-cost-item23"),
		"directional_drilling_cost_item24" : $val("directional-drilling-cost-item24"),
		"directional_drilling_cost_item25" : $val("directional-drilling-cost-item25"),
		"directional_drilling_cost_item26" : $val("directional-drilling-cost-item26"),
		"directional_drilling_cost_item27" : $val("directional-drilling-cost-item27"),
		"directional_drilling_cost_item28" : $val("directional-drilling-cost-item28"),
		"directional_drilling_cost_item29" : $val("directional-drilling-cost-item29"),
		"directional_drilling_cost_item30" : $val("directional-drilling-cost-item30"),
		"directional_drilling_cost_item31" : $val("directional-drilling-cost-item31"),

		// Mud Engineering
		"mud_engineering_qty_item0" : $val("mud-engineering-qty-item0"),
		"mud_engineering_cost_item0" : $val("mud-engineering-cost-item0"),

		// Aerated Drilling 
		"aerated_drilling_cost_item0" : $val("aerated-drilling-cost-item0"),
		"aerated_drilling_cost_item1" : $val("aerated-drilling-cost-item1"),
		"aerated_drilling_cost_item2" : $val("aerated-drilling-cost-item2"),
		"aerated_drilling_cost_item3" : $val("aerated-drilling-cost-item3"),
		"aerated_drilling_cost_item4" : $val("aerated-drilling-cost-item4"),
		"aerated_drilling_cost_item5" : $val("aerated-drilling-cost-item5"),
		"aerated_drilling_cost_item6" : $val("aerated-drilling-cost-item6"),
		"aerated_drilling_cost_item7" : $val("aerated-drilling-cost-item7"),
		"aerated_drilling_cost_item8" : $val("aerated-drilling-cost-item8"),
		"aerated_drilling_cost_item9" : $val("aerated-drilling-cost-item9"),
		"aerated_drilling_cost_item10" : $val("aerated-drilling-cost-item10"),
		"aerated_drilling_cost_item11" : $val("aerated-drilling-cost-item11"),
		"aerated_drilling_cost_item12" : $val("aerated-drilling-cost-item12"),
		"aerated_drilling_cost_item13" : $val("aerated-drilling-cost-item13"),
		"aerated_drilling_cost_item14" : $val("aerated-drilling-cost-item14"),
		"aerated_drilling_cost_item15" : $val("aerated-drilling-cost-item15"),
		"aerated_drilling_cost_item16" : $val("aerated-drilling-cost-item16"),
		"aerated_drilling_cost_item17" : $val("aerated-drilling-cost-item17"),
		"aerated_drilling_cost_item18" : $val("aerated-drilling-cost-item18"),
		"aerated_drilling_cost_item19" : $val("aerated-drilling-cost-item19"),
		"aerated_drilling_cost_item20" : $val("aerated-drilling-cost-item20"),

		// Jars and Shock
		"jars_shock_qty_item0" : $val("jars-shock-qty-item0"),
		"jars_shock_qty_item1" : $val("jars-shock-qty-item1"),
		"jars_shock_qty_item2" : $val("jars-shock-qty-item2"),
		"jars_shock_qty_item3" : $val("jars-shock-qty-item3"),
		"jars_shock_qty_item4" : $val("jars-shock-qty-item4"),
		"jars_shock_qty_item5" : $val("jars-shock-qty-item5"),

		"jars_shock_cost_item0" : $val("jars-shock-cost-item0"),
		"jars_shock_cost_item1" : $val("jars-shock-cost-item1"),
		"jars_shock_cost_item2" : $val("jars-shock-cost-item2"),
		"jars_shock_cost_item3" : $val("jars-shock-cost-item3"),
		"jars_shock_cost_item4" : $val("jars-shock-cost-item4"),
		"jars_shock_cost_item5" : $val("jars-shock-cost-item5"),

		// CHF Welding
		"chf_installation_cost_item0" : $val("chf-installation-cost-item0"),
		"chf_installation_cost_item1" : $val("chf-installation-cost-item1"),
		"chf_installation_cost_item2" : $val("chf-installation-cost-item2"),
		"chf_installation_cost_item3" : $val("chf-installation-cost-item3"),
		"chf_installation_cost_item4" : $val("chf-installation-cost-item4"),
		"chf_installation_cost_item5" : $val("chf-installation-cost-item5"),
		"chf_installation_cost_item6" : $val("chf-installation-cost-item6"),
		"chf_installation_cost_item7" : $val("chf-installation-cost-item7"),
		"chf_installation_cost_item8" : $val("chf-installation-cost-item8"),
		
		// Mud Logging
		"mud_logging_cost_item0" : $val("mud-logging-cost-item0"),
		"mud_logging_cost_item1" : $val("mud-logging-cost-item1"),

		// Casing Running
		"casing_running_cost_item0" : $val("casing-running-cost-item0"),

		"drilling_rig_cost_item0" : $val("drilling-rig-cost-item0"),
		"drilling_rig_cost_item1" : $val("drilling-rig-cost-item1"),
		"drilling_rig_cost_item2" : $val("drilling-rig-cost-item2"),
		"drilling_rig_cost_item3" : $val("drilling-rig-cost-item3"),
		"drilling_rig_cost_item4" : $val("drilling-rig-cost-item4"),
		"drilling_rig_cost_item5" : $val("drilling-rig-cost-item5"),
		"drilling_rig_cost_item6" : $val("drilling-rig-cost-item6"),
		"drilling_rig_cost_item8" : $val("drilling-rig-cost-item8"),
		"drilling_rig_cost_item9" : $val("drilling-rig-cost-item9"),

		// Drill Pipes
		"drill_pipes_qty_item0" : $val("drill-pipes-qty-item0"),
		"drill_pipes_qty_item1" : $val("drill-pipes-qty-item1"),
		"drill_pipes_qty_item2" : $val("drill-pipes-qty-item2"),
		"drill_pipes_qty_item3" : $val("drill-pipes-qty-item3"),
		
		"drill_pipes_cost_item0" : $val("drill-pipes-cost-item0"),
		"drill_pipes_cost_item1" : $val("drill-pipes-cost-item1"),
		"drill_pipes_cost_item2" : $val("drill-pipes-cost-item2"),
		"drill_pipes_cost_item3" : $val("drill-pipes-cost-item3"),

		// Completion Tests
		"completion_test_cost_item0" : $val("completion-test-cost-item0"),
		"completion_test_cost_item1" : $val("completion-test-cost-item1"),

		// Other Cementing Services
		"other_cementing_services_cost_item0" : $val("other-cementing-services-cost-item0"),

		// Equipmental Rental
		"equipmental_rental_qty_item0" : $val("equipmental-rental-qty-item0"),
		"equipmental_rental_qty_item1" : $val("equipmental-rental-qty-item1"),
		"equipmental_rental_qty_item2" : $val("equipmental-rental-qty-item2"),
		"equipmental_rental_qty_item3" : $val("equipmental-rental-qty-item3"),
		"equipmental_rental_qty_item4" : $val("equipmental-rental-qty-item4"),
		"equipmental_rental_qty_item5" : $val("equipmental-rental-qty-item5"),
		"equipmental_rental_qty_item6" : $val("equipmental-rental-qty-item6"),

		"equipmental_rental_cost_item0" : $val("equipmental-rental-cost-item0"),
		"equipmental_rental_cost_item1" : $val("equipmental-rental-cost-item1"),
		"equipmental_rental_cost_item2" : $val("equipmental-rental-cost-item2"),
		"equipmental_rental_cost_item3" : $val("equipmental-rental-cost-item3"),
		"equipmental_rental_cost_item4" : $val("equipmental-rental-cost-item4"),
		"equipmental_rental_cost_item5" : $val("equipmental-rental-cost-item5"),
		"equipmental_rental_cost_item6" : $val("equipmental-rental-cost-item6"),

		// Option for Running the Permutation
		"run_option" : $val("run-option"),
		"run_option_casing" : $val("run-option-casing")
	};
}

function getCoverSheetValues(){
	return [
	"fuels",
	"lubricants",
	"mud_and_chemicals",
	"cements_and_additives",
	"rockbits",
	"drilling_supplies",
	"casings",
	"wellhead",
	"cementing_services",
	"directional_drilling_services",
	"mud_engineering_services",
	"aerated_drilling_services",
	"jars_and_shock_tools",
	"chf_welding_services",
	"mud_logging_services",
	"casing_running_services",
	"drilling_rig_services",
	"drill_pipes",
	"completion_test_wireline",
	"other_cementing_services",
	"handling_hauling_towing",
	"rig_mobilization_charges",
	"rig_oml_daily_rate",
	"depreciation",
	"insurance",
	"genex_daily_rate",
	"thermaprime",
	"DG",
	"interisland_cost",
	"total",
	"materials_total",
	"services_total",
	"rig_allocated_total"
	]
}

function getPermutationValues(){
	return [
	"surface_from",
	"surface_to",
	"surface_increment",
	"intermediate_from",
	"intermediate_to",
	"intermediate_increment",
	"production_casing_from",
	"production_casing_to",
	"production_casing_increment",
	"production_liner_1_from",
	"production_liner_1_to",
	"production_liner_1_increment",
	"production_liner_2_from",
	"production_liner_2_to",
	"production_liner_2_increment",
	"production_liner_3_from",
	"production_liner_3_to",
	"production_liner_3_increment",
	]
}
