{
    "pwd_fliner1": True,
    "rent_drill_pipes": False,
    "yes_if_without_pre-installed_csg": True,
    "target_depth": 2500.0,
    "reline": False,
    "no_of_Joints": 311.0,
    "rh_or_bh": u"Big Hole",
    "b23": False,
    "forex_ph_us": 51.0,
    "drilling_row_total": {
        "prodn_liner_2": 12.0,
        "prodn_liner_3": 0,
        "reline": 0,
        "prodn_liner_1": 8.0,
        "surface": 6.0,
        "production": 13.0,
        "intermediate": 9.0
    },
    "project_loc": u"LGBU",
    "drilling_days": 41.0,
    "aerated_prodn_liner_2": True,
    "rig": u"Rig 2",
    "aerated_prodn_liner_1": True,
    "well_name": u"438D",
    "aerated_intermediate": True,
    "interisland_rig_move": False,
    "mob/demob_drillpipes": u"WITHIN SITE",
    "aerated_prodn_casing": True,
    "double_liner": True,
    "dhv_2": 0.0,
    "prodn_liner_3": False,
    "chf": u"TESCO",
    "dhv_1": False,
    "pwd_fliner2": True,
    "fe_fliner1": False,
    "diesel_ph_us": 36.0,
    "aerated_surface": True,
    "fe_fliner2": False,
    "total_days": 61.0,
    "target_rop": 61.0,
    "rig_move_days": 13.0,
    "mud_logging": True,
    "rig_move_from": u"PAD",
    "regular_bottom_section_for_bh": False
}